bog_many_to_many/config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  resources :creatures

  resources :tags

end

bog_many_to_many/app/models/creature.rb
class Creature < ActiveRecord::Base
  has_and_belongs_to_many :tags
end

bog_many_to_many/app/models/creatures_tags.rb
class CreaturesTags < ActiveRecord::Base
  belongs_to :creature
  belongs_to :tag
end

bog_many_to_many/app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :creatures
end

bog_many_to_many/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bog_many_to_many/app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  def index
    @creatures = Creature.all
  end

  def new
    @creature = Creature.new
    @tags = Tag.all
  end

  def show
    @creature = Creature.find(params[:id])
    @tags = @creature.tags
  end

  def create
    # render json: params

    c = Creature.create(creature_params)
    update_tags c

    redirect_to creatures_path
  end

  def update
    c = Creature.find params[:id]
    c.update creature_params

    c.tags.clear
    update_tags c

    redirect_to c
  end

  def edit
    @creature = Creature.find params[:id]
    @tags = Tag.all
  end

  def destroy
    Creature.find(params[:id]).delete
    redirect_to creatures_path
  end

  private

  def update_tags creature
    creature_tags = params[:creature][:tag_ids]
    creature_tags.each do |id|
      creature.tags << Tag.find(id) unless id.blank?
    end
  end

  def creature_params
    params.require(:creature).permit(:name, :description)
  end
end

bog_many_to_many/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

bog_many_to_many/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find params[:id]
  end

  def new
    @tag = Tag.new
  end

  def create
    tag = Tag.create(tag_params)


    redirect_to tags_path
  end

  def update
    t = Tag.find params[:id]
    t.update tag_params


    redirect_to tags_path
  end

  def edit
    @tag = Tag.find params[:id]
    @tags = Tag.all
  end

  def destroy
        #render json: params

        tag = Tag.find(params[:id])

        if tag.creatures.empty?
            tag.delete
        end

        redirect_to tags_path
    end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end

end

bog_many_to_many/app/helpers/application_helper.rb
module ApplicationHelper
end

bog_many_to_many/app/helpers/creatures_helper.rb
module CreaturesHelper
end

bog_many_to_many/app/helpers/main_helper.rb
module MainHelper
end

bog_many_to_many/app/helpers/tags_helper.rb
module TagsHelper
end

bog_many_to_many/app/views/creatures/_form.html.erb
<%= bootstrap_form_for @creature do |c| %>
  <%= c.text_field :name %>
  <%= c.text_area :description %>

  <%= c.collection_check_boxes :tag_ids, @tags, :id, :name %>

  <%= c.primary %>
<% end %>

bog_many_to_many/app/views/creatures/edit.html.erb
<%= link_to "&larr; Back".html_safe, creatures_path, class: "btn btn-primary" %>

<h2>Edit a Creature</h2>

<%= render 'creatures/form' %>

bog_many_to_many/app/views/creatures/index.html.erb
<h2>Creature List</h2>

<%= link_to "&larr; Back".html_safe, root_path, class: "btn btn-primary margin-bottom" %>
<%= link_to "New", new_creature_path, class: "btn btn-info pull-right margin-bottom" %>

<% @creatures.each do |creature| %>
<div class="well">
  <h3><%= creature.name %></h3>
  <p><%= creature.description %></p>
  <%= link_to "", creature, method: :delete, class: 'btn btn-danger btn-sm glyphicon glyphicon-trash pull-right margin-left', data: {confirm: "Are you sure?"} %>
  <%= link_to "", edit_creature_path(creature), class: 'btn btn-primary btn-sm glyphicon glyphicon-pencil pull-right margin-left' %>
  <p><%= link_to "Permalink", creature %></p>
  <p>
  <% creature.tags.each do |tag| %>
    <%= link_to "##{tag.name}", tag %>
  <% end %>
  </p>
</div>
<% end %>

bog_many_to_many/app/views/creatures/new.html.erb
<%= link_to "&larr; Back".html_safe, creatures_path, class: "btn btn-primary" %>

<h2>Create a new Creature</h2>

<%= render 'creatures/form' %>

bog_many_to_many/app/views/creatures/show.html.erb
<%= link_to "&larr; Back".html_safe, creatures_path, class: "btn btn-primary" %>

<h2><%= @creature.name %></h2>

<div class="well">
  <p><%= @creature.description %></p>
  <ul>
  <% @tags.each do |tag| %>
    <li><%= tag.name %></li>
  <% end %>
  </ul>
</div>

bog_many_to_many/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Latest compiled and minified CSS & JS -->
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <title>Bog App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <h1>Bog</h1>
    <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
      <%= yield %>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
      <h2>Links</h2>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Bog", creatures_path %></li>
        <li><%= link_to "Tags", tags_path %></li>
      </ul>
    </div>
  </div>
</body>
</html>

bog_many_to_many/app/views/main/index.html.erb
<h1>Welcome to the Legendary Bog of South Lake Union</h1>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<%= link_to "Go to my Bog", creatures_path, class: "btn btn-primary" %>

bog_many_to_many/app/views/tags/edit.html.erb
<%= link_to "&larr; Back".html_safe, tags_path, class: "btn btn-primary" %>

<h2>Edit Tag</h2>

<%= bootstrap_form_for @tag do |c| %>
  <%= c.text_field :name %>

  <%= c.primary %>
<% end %>

bog_many_to_many/app/views/tags/index.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <h2 class="center-text">All Tags</h2>
    <%= link_to "View All Creatures", creatures_path, class: "pull-left btn btn-danger" %>
    <%= link_to "New Tag", new_tag_path, class: "pull-right btn btn-warning" %>
  </div>

<% @tags.each do |tag| %>
<div class="well well-sm creature-card col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <h3><%= link_to tag.name, tag %></h3>

  <div class="button-cluster">
    <% if tag.creatures.empty? %>
      <%= link_to "", tag, method: :delete, class: ' pull-right delete-link glyphicon glyphicon-trash margin-right btn btn-danger', title: "Delete", data: {confirm: "Are you sure?"} %>
    <% else %>
      <%= link_to "", "", class: ' pull-right delete-link-disabled glyphicon glyphicon-trash margin-left', title: "Tag is in use by creatures and cannot be deleted.", data: {confirm: "Are you sure?"} %>
    <% end %>
  </div>


  <%= link_to "", edit_tag_path(tag), class: 'btn btn-primary btn-sm glyphicon glyphicon-pencil pull-right margin-left' %>

</div>
<% end %>

</div>

bog_many_to_many/app/views/tags/new.html.erb
<%= link_to "&larr; Back".html_safe, tags_path, class: "btn btn-primary" %>

<h2>Create a new tag</h2>

<%= bootstrap_form_for @tag do |c| %>
  <%= c.text_field :name %>

  <%= c.primary %>
<% end %>

bog_many_to_many/app/views/tags/show.html.erb
<h2>#<%= @tag.name %></h2>

<% @tag.creatures.each do |creature| %>
<div class="well">
  <%= link_to creature.name, creature %>
</div>
<% end %>